name: CI for macOS

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        brew install curl ngrok

    - name: Auth ngrok
      run: ngrok authtoken ${{ secrets.NGROK_AUTH_TOKEN }}

    - name: Start ngrok tunnel
      run: |
        ngrok tcp 3389 &

    - name: Run your application
      run: |
        # Tambahkan langkah untuk menjalankan aplikasi Anda
        echo "App is running"
