name: CI

on: [push, workflow_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Download ngrok
      run: |
        wget https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.zip -O ngrok.zip

    - name: Extract ngrok
      run: |
        unzip ngrok.zip -d ngrok
        chmod +x ngrok/ngrok  # Berikan izin eksekusi untuk file ngrok

    - name: Auth ngrok
      run: |
        ./ngrok/ngrok authtoken $NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}

    - name: Enable SSH
      run: |
        sudo apt update
        sudo apt install -y openssh-server
        sudo systemctl enable ssh
        sudo systemctl start ssh
        sudo ufw allow ssh
        sudo ufw allow 3389  # Pastikan port 3389 terbuka untuk RDP

    - name: Create ngrok Tunnel
      run: |
        nohup ./ngrok/ngrok tcp 3389 &  # Jalankan ngrok di background untuk membuat tunnel
        sleep 5  # Beri waktu agar ngrok dapat membuat tunnel

    - name: Display ngrok tunnel URL
      run: |
        curl -s localhost:4040/api/tunnels  # Menampilkan URL ngrok untuk akses RDP
