name: CI

on: [push, workflow_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Download
      run: curl -L https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.zip -o ngrok.zip
    - name: Extract
      run: unzip ngrok.zip
    - name: Auth
      run: ./ngrok authtoken $NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
    - name: Enable Remote Desktop (RDP)
      run: |
        sudo apt update
        sudo apt install -y xrdp
        sudo systemctl enable xrdp
        sudo systemctl start xrdp
    - name: Set RDP Password
      run: echo "runneradmin:P@ssw0rd!" | sudo chpasswd
    - name: Create Tunnel
      run: ./ngrok tcp 3389
