name: Setup VNC Server and Remote Login

on:
  push:
    branches:
      - main

jobs:
  setup-vnc:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Enable Remote Login (SSH)
      run: |
        # Mengaktifkan remote login (SSH)
        setremotelogin=$(systemsetup -getremotelogin)
        if [[ "$setremotelogin" != *"On"* ]]; then
          sudo systemsetup -setremotelogin on
          echo "Remote login (SSH) diaktifkan."
        else
          echo "Remote login (SSH) sudah aktif."
        fi

    - name: Install TigerVNC if not installed
      run: |
        if ! command -v vncserver &> /dev/null; then
          echo "VNC server tidak ditemukan, menginstall TigerVNC..."
          brew install tiger-vnc
        else
          echo "VNC server sudah terinstal."
        fi

    - name: Start VNC server if not running
      run: |
        if ! pgrep -f "vncserver :1" > /dev/null; then
          echo "Memulai VNC server..."
          /opt/homebrew/bin/vncserver :1
          echo "VNC server berjalan pada port 5901"
        else
          echo "VNC server sudah berjalan pada port 5901."
        fi
