name: CI

on: [push, workflow_dispatch]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install ngrok
      run: |
        curl -sSL https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-darwin-amd64.zip -o ngrok.zip
        unzip ngrok.zip
        rm ngrok.zip

    - name: Auth ngrok
      run: ./ngrok authtoken ${{ secrets.NGROK_AUTH_TOKEN }}

    - name: Enable Remote Desktop (RDP)
      run: |
        # Mengaktifkan akses RDP, namun macOS tidak menggunakan registry seperti Windows
        # Sebagai pengganti, kita bisa memastikan aplikasi yang mendukung RDP sudah berjalan.
        sudo systemsetup -setremotelogin on

    - name: Create ngrok Tunnel for RDP
      run: |
        ./ngrok tcp 3389 &
        sleep 10 # Menunggu tunnel untuk stabil

    - name: Run your application or services
      run: |
        echo "Your app or service is now running!"
