name: CI

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Download ngrok
      run: Invoke-WebRequest https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-windows-amd64.zip -OutFile ngrok.zip

    - name: Extract ngrok
      run: Expand-Archive ngrok.zip -DestinationPath ngrok

    - name: Auth ngrok
      run: .\ngrok\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}

    - name: Enable Terminal Services (TS)
      run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -name "fDenyTSConnections" -Value 0

    - name: Allow RDP through Windows Firewall
      run: Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

    - name: Set RDP user authentication
      run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1

    - name: Set local user password
      run: Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "P@ssw0rd!" -Force)

    - name: Start ngrok tunnel in background
      id: ngrok
      run: |
        Start-Process .\ngrok\ngrok.exe -ArgumentList "tcp 3389" -NoNewWindow
        # Wait for ngrok to initialize
        Start-Sleep -Seconds 5
        # Get the ngrok URL
        $ngrok_url = curl --silent --max-time 10 http://localhost:4040/api/tunnels | ConvertFrom-Json | Select-Object -ExpandProperty tunnels | Select-Object -First 1 | Select-Object -ExpandProperty public_url
        Write-Host "Ngrok URL: $ngrok_url"
        echo "::set-output name=ngrok_url::$ngrok_url"

    - name: Keep GitHub Action Running
      run: |
        # Infinite loop to keep the action running and ngrok alive
        Write-Host "GitHub Action is running and ngrok tunnel is open. Press Ctrl+C to stop."
        while ($true) { Start-Sleep -Seconds 3600 }
      
    - name: Display ngrok URL
      run: |
        echo "Ngrok tunnel is available at: ${{ steps.ngrok.outputs.ngrok_url }}"
