name: Host Website

on: [push, workflow_dispatch]

jobs:
  host-website:

    runs-on: windows-latest

    steps:
    - name: Download ngrok
      run: Invoke-WebRequest https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-windows-amd64.zip -OutFile ngrok.zip
    - name: Extract ngrok
      run: Expand-Archive ngrok.zip
    - name: Auth with ngrok
      run: .\ngrok\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
    - name: Install Python
      run: choco install python --version 3.10.9 -y
    - name: Start HTTP Server
      run: python -m http.server 8000
      working-directory: ./website
      background: true
    - name: Create ngrok Tunnel
      run: .\ngrok\ngrok.exe http 8000
