name: ubuntu

on: [push, workflow_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Update and Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y wget unzip openssh-server

    - name: Download ngrok
      run: wget https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.zip -O ngrok.zip

    - name: Extract ngrok
      run: unzip ngrok.zip

    - name: Auth ngrok
      run: ./ngrok authtoken $NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}

    - name: Start SSH Service
      run: |
        sudo systemctl enable ssh
        sudo systemctl start ssh

    - name: Configure SSH
      run: |
        sudo sed -i 's/#PasswordAuthentication yes/PasswordAuthentication yes/' /etc/ssh/sshd_config
        sudo systemctl restart ssh

    - name: Create Tunnel
      run: ./ngrok tcp 22
